@apiURL = http://localhost:8080/boards
@apiURL2 = http://localhost:8080

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJlbWFpbCI6Im5pY29AbmljbyIsIm5hbWUiOiJuaWNvIiwibGFzdG5hbWUiOiJuaWNvIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjAxOTE5NTcsImV4cCI6MTc2MDE5MjU1N30.UCjA7hBPTIZYi5CEX8YfimkSQx2jA8IqLltamkP49Bk

GET {{apiURL}}
Authorization: Bearer {{token}}

###

POST {{apiURL}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "test delete function"
}

###

POST {{apiURL}}/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "testing@testtt.com"
}

###

DELETE  {{apiURL}}/10
Authorization: Bearer {{token}}
Content-Type: application/json

###

POST {{apiURL2}}/refresh
Authorization: Bearer {{ token }}
Content-Type: application/json

{
    "expires_at": 1758959885,
    "token": "testToken"
}

